
GET http://localhost:5000/get

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "userName":"suresh",
    "userEmail":"suresh@gmail.com",
    "userPassword":"qwe123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "userEmail":"venkata@gmail.com",
    "userPassword":"qwee123"
}

###
POST https://superset.haathi.ai/api/v1/security/login
Content-Type: application/json

{ "password": "admin",
  "provider": "db",
  "refresh": true,
  "username": "admin"
}
