


GET http://localhost:5000/get

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "userName":"ggg",
    "userEmail":"ggg@gmail.com",
    "userPassword":"ggg123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "userName":"ashok",
    "userPassword":"ashok@123"
}
